import type { Product } from "@/types";

export const products: Product[] = [
  {
    id: "mercimek",
    name: "Mercimek Çorbası",
    description: "Klasik usulde hazırlanan, tereyağlı sosla tamamlanan ev yapımı mercimek çorbası.",
    price: 120,
    categoryId: "soups",
    category: "Çorbalar",
    image: "/images/food/mercimek-corbasi.jpg",
    weight: "300 ml",
    allergens: ["Süt ürünleri", "Gluten"],
    tags: ["Popüler", "Vejetaryen", "Günün Yemeği"],
    status: "active",
    featured: true,
  },
  {
    id: "tas-kebabi",
    name: "Tas Kebabı",
    description: "Dana eti, mevsim sebzeleri ve lokantamızın ağır pişmiş özel sosu.",
    price: 320,
    categoryId: "kebabs",
    category: "Kebaplar",
    image: "/images/food/tas-kebabi.jpg",
    weight: "300 gr",
    allergens: ["Gluten"],
    tags: ["Şefin Önerisi", "Günün Yemeği"],
    status: "active",
    featured: true,
  },
  {
    id: "kuzu-tandir",
    name: "Kuzu Tandır",
    description: "Ağır ateşte uzun süre pişirilmiş, lokantamızın imza kuzu tandırı.",
    price: 420,
    categoryId: "kebabs",
    category: "Kebaplar",
    image: "/images/food/kuzu-tandir.jpg",
    weight: "350 gr",
    allergens: ["Süt ürünleri"],
    tags: ["Şefin Önerisi", "Popüler"],
    status: "active",
    featured: true,
  },
  {
    id: "pirinc-pilavi",
    name: "Pirinç Pilavı",
    description: "Tereyağlı, tane tane Baldo pirinç pilavı.",
    price: 90,
    categoryId: "mains",
    category: "Ana Yemekler",
    image: "/images/food/pirinc-pilavi.jpg",
    weight: "180 gr",
    allergens: ["Süt ürünleri"],
    tags: ["Vejetaryen"],
    status: "active",
    featured: true,
  },
  {
    id: "firin-sutlac",
    name: "Fırın Sütlaç",
    description: "Geleneksel usulde fırınlanmış, günlük manda sütüyle hazırlanan sütlaç.",
    price: 140,
    categoryId: "dessert",
    category: "Tatlılar",
    image: "/images/food/firin-sutlac.jpg",
    weight: "220 gr",
    allergens: ["Süt ürünleri"],
    tags: ["Popüler"],
    status: "active",
    featured: true,
  },
  {
    id: "kuru-fasulye",
    name: "Etli Kuru Fasulye",
    description: "İspir fasulyesi, kuşbaşı dana eti ve sade lokanta salçasıyla.",
    price: 260,
    categoryId: "mains",
    category: "Ana Yemekler",
    image: "/images/food/etli-kuru-fasulye.jpg",
    weight: "320 gr",
    allergens: [],
    tags: ["Günün Yemeği"],
    status: "sold-out",
  },
  {
    id: "izgara-kofte",
    name: "Izgara Köfte",
    description: "Kasap usulü dana köfte, közlenmiş biber ve domates ile.",
    price: 350,
    categoryId: "grill",
    category: "Izgaralar",
    image: "/images/food/izgara-kofte.jpg",
    weight: "280 gr",
    allergens: ["Gluten", "Yumurta"],
    tags: ["Yeni"],
    status: "active",
  },
  {
    id: "ayran",
    name: "Yayık Ayranı",
    description: "Bol köpüklü, günlük yoğurtla hazırlanan geleneksel yayık ayranı.",
    price: 55,
    categoryId: "drinks",
    category: "İçecekler",
    image: "/images/food/yayik-ayrani.jpg",
    weight: "300 ml",
    allergens: ["Süt ürünleri"],
    tags: [],
    status: "active",
  },
  {
    id: "ezogelin-corbasi",
    name: "Ezogelin Çorbası",
    description: "Kırmızı mercimek, bulgur ve pirincin nane ile buluştuğu geleneksel lokanta çorbası.",
    price: 125,
    categoryId: "soups",
    category: "Çorbalar",
    image: "/images/food/mercimek-corbasi.jpg",
    weight: "300 ml",
    allergens: ["Gluten"],
    tags: ["Acılı", "Vejetaryen"],
    status: "active",
  },
  {
    id: "tarhana-corbasi",
    name: "Tarhana Çorbası",
    description: "Ev yapımı tarhana, domates ve kuru nane ile ağır ağır pişirilen Anadolu klasiği.",
    price: 115,
    categoryId: "soups",
    category: "Çorbalar",
    image: "/images/food/mercimek-corbasi.jpg",
    weight: "300 ml",
    allergens: ["Gluten", "Süt ürünleri"],
    tags: ["Ev Yapımı"],
    status: "active",
  },
  {
    id: "yayla-corbasi",
    name: "Yayla Çorbası",
    description: "Yoğurt, pirinç ve kuru naneyle hazırlanan ferah ve kıvamlı yayla çorbası.",
    price: 125,
    categoryId: "soups",
    category: "Çorbalar",
    image: "/images/food/mercimek-corbasi.jpg",
    weight: "300 ml",
    allergens: ["Süt ürünleri", "Yumurta"],
    tags: ["Vejetaryen"],
    status: "active",
  },
  {
    id: "iskembe-corbasi",
    name: "İşkembe Çorbası",
    description: "Terbiyesi ve sarımsaklı sirkesiyle servis edilen usulüne uygun dana işkembe çorbası.",
    price: 180,
    categoryId: "soups",
    category: "Çorbalar",
    image: "/images/food/mercimek-corbasi.jpg",
    weight: "300 ml",
    allergens: ["Gluten", "Yumurta", "Süt ürünleri"],
    tags: ["Lokanta Klasiği"],
    status: "active",
  },
  {
    id: "dugun-corbasi",
    name: "Düğün Çorbası",
    description: "Didiklenmiş kuzu eti ve limonlu terbiyeyle hazırlanan geleneksel düğün çorbası.",
    price: 145,
    categoryId: "soups",
    category: "Çorbalar",
    image: "/images/food/mercimek-corbasi.jpg",
    weight: "300 ml",
    allergens: ["Gluten", "Yumurta", "Süt ürünleri"],
    tags: ["Günün Çorbası"],
    status: "active",
  },
  {
    id: "tavuk-suyu-corbasi",
    name: "Tavuk Suyu Çorbası",
    description: "Kemik suyunda pişen tel şehriye ve didik tavuk etiyle hazırlanan şifalı çorba.",
    price: 155,
    categoryId: "soups",
    category: "Çorbalar",
    image: "/images/food/mercimek-corbasi.jpg",
    weight: "300 ml",
    allergens: ["Gluten"],
    tags: ["Şefin Önerisi"],
    status: "active",
  },
  {
    id: "domates-corbasi",
    name: "Domates Çorbası",
    description: "Olgun domates, tereyağı ve fesleğenle pişirilip kaşarla tamamlanan yoğun lezzet.",
    price: 120,
    categoryId: "soups",
    category: "Çorbalar",
    image: "/images/food/mercimek-corbasi.jpg",
    weight: "300 ml",
    allergens: ["Gluten", "Süt ürünleri"],
    tags: ["Vejetaryen"],
    status: "active",
  },
  {
    id: "sebze-corbasi",
    name: "Sebze Çorbası",
    description: "Mevsim sebzeleri, zeytinyağı ve taze otlarla hazırlanan hafif lokanta çorbası.",
    price: 120,
    categoryId: "soups",
    category: "Çorbalar",
    image: "/images/food/mercimek-corbasi.jpg",
    weight: "300 ml",
    allergens: [],
    tags: ["Vegan", "Hafif"],
    status: "active",
  },
  {
    id: "beyran-corbasi",
    name: "Beyran Çorbası",
    description: "Kuzu eti, pirinç, sarımsak ve acı biberle yüksek ateşte hazırlanan yöresel çorba.",
    price: 240,
    categoryId: "soups",
    category: "Çorbalar",
    image: "/images/food/mercimek-corbasi.jpg",
    weight: "320 ml",
    allergens: [],
    tags: ["Acılı", "Yöresel"],
    status: "active",
    featured: true,
  },
  {
    id: "kelle-paca-corbasi",
    name: "Kelle Paça Çorbası",
    description: "Uzun saatler kaynatılan dana paça ve kelle etiyle hazırlanan yoğun kemik suyu çorbası.",
    price: 220,
    categoryId: "soups",
    category: "Çorbalar",
    image: "/images/food/mercimek-corbasi.jpg",
    weight: "320 ml",
    allergens: [],
    tags: ["Lokanta Klasiği"],
    status: "sold-out",
  },
  {
    id: "sehriye-corbasi",
    name: "Şehriye Çorbası",
    description: "Domatesli tavuk suyunda tel şehriye ve maydanozla hazırlanan günlük çorba.",
    price: 115,
    categoryId: "soups",
    category: "Çorbalar",
    image: "/images/food/mercimek-corbasi.jpg",
    weight: "300 ml",
    allergens: ["Gluten"],
    tags: ["Günün Çorbası"],
    status: "active",
  },
  {
    id: "tavuk-sis",
    name: "Tavuk Şiş",
    description: "Özel baharatlarla marine edilmiş tavuk parçaları, köz biber ve domates eşliğinde.",
    price: 310,
    categoryId: "grill",
    category: "Izgaralar",
    image: "/images/food/izgara-kofte.jpg",
    weight: "300 gr",
    allergens: ["Süt ürünleri"],
    tags: ["Popüler"],
    status: "active",
  },
  {
    id: "kasap-sucuk",
    name: "Kasap Sucuk",
    description: "Odun kömüründe pişirilen baharatlı dana sucuk, közlenmiş sebzeler ve sumaklı soğanla.",
    price: 330,
    categoryId: "grill",
    category: "Izgaralar",
    image: "/images/food/izgara-kofte.jpg",
    weight: "250 gr",
    allergens: [],
    tags: ["Acılı"],
    status: "active",
  },
  {
    id: "karisik-izgara",
    name: "Karışık Izgara",
    description: "Köfte, tavuk şiş, kuzu pirzola ve sucuktan oluşan bol çeşitli ızgara tabağı.",
    price: 560,
    categoryId: "grill",
    category: "Izgaralar",
    image: "/images/food/kuzu-tandir.jpg",
    weight: "480 gr",
    allergens: ["Gluten", "Süt ürünleri", "Yumurta"],
    tags: ["Şefin Önerisi", "Paylaşmalık"],
    status: "active",
    featured: true,
  },
  {
    id: "nohut-yemegi",
    name: "Etli Nohut Yemeği",
    description: "Koçbaşı nohut ve kuşbaşı dana etiyle bakır tencerede ağır ağır pişirilen ev yemeği.",
    price: 250,
    categoryId: "mains",
    category: "Ana Yemekler",
    image: "/images/food/etli-kuru-fasulye.jpg",
    weight: "320 gr",
    allergens: [],
    tags: ["Günün Yemeği"],
    status: "active",
  },
  {
    id: "patlican-musakka",
    name: "Patlıcan Musakka",
    description: "Kızarmış patlıcan, dana kıyma ve domates sosla fırında pişirilen lokanta usulü musakka.",
    price: 270,
    categoryId: "mains",
    category: "Ana Yemekler",
    image: "/images/food/tas-kebabi.jpg",
    weight: "300 gr",
    allergens: [],
    tags: ["Ev Yemeği"],
    status: "active",
  },
  {
    id: "zeytinyagli-taze-fasulye",
    name: "Zeytinyağlı Taze Fasulye",
    description: "Taze fasulye, domates ve soğanla zeytinyağında pişirilen serin servis edilen klasik.",
    price: 220,
    categoryId: "mains",
    category: "Ana Yemekler",
    image: "/images/food/etli-kuru-fasulye.jpg",
    weight: "280 gr",
    allergens: [],
    tags: ["Vegan", "Zeytinyağlı"],
    status: "active",
  },
  {
    id: "tavuk-sote",
    name: "Tavuk Sote",
    description: "Tavuk parçaları, renkli biberler, mantar ve domatesle yüksek ateşte sotelenir.",
    price: 285,
    categoryId: "mains",
    category: "Ana Yemekler",
    image: "/images/food/tas-kebabi.jpg",
    weight: "320 gr",
    allergens: [],
    tags: ["Günün Yemeği"],
    status: "active",
  },
  {
    id: "izmir-kofte",
    name: "İzmir Köfte",
    description: "Dana köfte, patates ve biberin domates sosunda fırınlandığı geleneksel ana yemek.",
    price: 300,
    categoryId: "mains",
    category: "Ana Yemekler",
    image: "/images/food/izgara-kofte.jpg",
    weight: "340 gr",
    allergens: ["Gluten", "Yumurta"],
    tags: ["Lokanta Klasiği"],
    status: "active",
  },
  {
    id: "etli-bezelye",
    name: "Etli Bezelye",
    description: "Kuşbaşı dana eti, bezelye, havuç ve patatesle tencere usulü pişirilen günlük yemek.",
    price: 280,
    categoryId: "mains",
    category: "Ana Yemekler",
    image: "/images/food/tas-kebabi.jpg",
    weight: "320 gr",
    allergens: [],
    tags: ["Ev Yemeği"],
    status: "active",
  },
  {
    id: "patlican-oturtma",
    name: "Patlıcan Oturtma",
    description: "Dilim patlıcan, baharatlı kıyma ve sarımsaklı domates sosla fırında hazırlanır.",
    price: 275,
    categoryId: "mains",
    category: "Ana Yemekler",
    image: "/images/food/tas-kebabi.jpg",
    weight: "300 gr",
    allergens: [],
    tags: ["Ev Yemeği"],
    status: "sold-out",
  },
  {
    id: "salgam-suyu",
    name: "Şalgam Suyu",
    description: "Mor havuç ve bulgur mayasıyla fermente edilmiş geleneksel acılı şalgam suyu.",
    price: 50,
    categoryId: "drinks",
    category: "İçecekler",
    image: "/images/food/yayik-ayrani.jpg",
    weight: "330 ml",
    allergens: ["Gluten"],
    tags: ["Acılı"],
    status: "active",
  },
  {
    id: "maden-suyu",
    name: "Maden Suyu",
    description: "Soğuk servis edilen doğal mineralli sade maden suyu.",
    price: 35,
    categoryId: "drinks",
    category: "İçecekler",
    image: "/images/food/yayik-ayrani.jpg",
    weight: "200 ml",
    allergens: [],
    tags: [],
    status: "active",
  },
  {
    id: "su",
    name: "Doğal Kaynak Suyu",
    description: "Cam şişede soğuk servis edilen doğal kaynak suyu.",
    price: 25,
    categoryId: "drinks",
    category: "İçecekler",
    image: "/images/food/yayik-ayrani.jpg",
    weight: "330 ml",
    allergens: [],
    tags: [],
    status: "active",
  },
  {
    id: "kola",
    name: "Kola",
    description: "Buz gibi servis edilen klasik gazlı içecek.",
    price: 60,
    categoryId: "drinks",
    category: "İçecekler",
    image: "/images/food/yayik-ayrani.jpg",
    weight: "330 ml",
    allergens: [],
    tags: [],
    status: "active",
  },
  {
    id: "gazoz",
    name: "Sade Gazoz",
    description: "Geleneksel aromalı, ferahlatıcı ve soğuk servis edilen sade gazoz.",
    price: 55,
    categoryId: "drinks",
    category: "İçecekler",
    image: "/images/food/yayik-ayrani.jpg",
    weight: "250 ml",
    allergens: [],
    tags: ["Nostaljik"],
    status: "active",
  },
  {
    id: "turk-kahvesi",
    name: "Türk Kahvesi",
    description: "Bakır cezvede ağır ateşte pişirilen köpüklü geleneksel Türk kahvesi.",
    price: 75,
    categoryId: "drinks",
    category: "İçecekler",
    image: "/images/food/yayik-ayrani.jpg",
    weight: "70 ml",
    allergens: [],
    tags: ["Geleneksel"],
    status: "active",
  },
  {
    id: "demleme-cay",
    name: "Demleme Çay",
    description: "İnce belli bardakta taze demlenmiş sıcak Rize çayı.",
    price: 25,
    categoryId: "drinks",
    category: "İçecekler",
    image: "/images/food/yayik-ayrani.jpg",
    weight: "120 ml",
    allergens: [],
    tags: [],
    status: "active",
  },
  {
    id: "ev-yapimi-limonata",
    name: "Ev Yapımı Limonata",
    description: "Taze limon, nane ve az şekerle günlük hazırlanan ferahlatıcı limonata.",
    price: 85,
    categoryId: "drinks",
    category: "İçecekler",
    image: "/images/food/yayik-ayrani.jpg",
    weight: "300 ml",
    allergens: [],
    tags: ["Ev Yapımı"],
    status: "active",
    featured: true,
  },
  {
    id: "hosaf",
    name: "Günlük Hoşaf",
    description: "Mevsimine göre kuru üzüm, kayısı veya erikle günlük kaynatılan ev hoşafı.",
    price: 70,
    categoryId: "drinks",
    category: "İçecekler",
    image: "/images/food/yayik-ayrani.jpg",
    weight: "300 ml",
    allergens: [],
    tags: ["Ev Yapımı"],
    status: "active",
  },
  {
    id: "iskender-kebabi",
    name: "Bursa İskender Kebabı",
    description: "Tırnak pide üzerinde döner, domates sosu, kızgın tereyağı ve yoğurtla servis edilir.",
    price: 395,
    categoryId: "kebabs",
    category: "Kebaplar",
    image: "/images/food/kuzu-tandir.jpg",
    weight: "360 gr",
    allergens: ["Gluten", "Süt ürünleri"],
    tags: ["Bursa Lezzeti", "Şefin Önerisi"],
    status: "active",
    featured: true,
  },
  {
    id: "kazandibi",
    name: "Kazandibi",
    description: "Altı usulünce karamelize edilmiş, ipeksi kıvamlı geleneksel sütlü tatlı.",
    price: 140,
    categoryId: "dessert",
    category: "Tatlılar",
    image: "/images/food/firin-sutlac.jpg",
    weight: "200 gr",
    allergens: ["Süt ürünleri", "Gluten"],
    tags: ["Sütlü Tatlı"],
    status: "active",
  },
  {
    id: "tavuk-gogsu",
    name: "Tavuk Göğsü",
    description: "Geleneksel reçeteyle hazırlanan, tarçınla servis edilen hafif ve lifli sütlü tatlı.",
    price: 145,
    categoryId: "dessert",
    category: "Tatlılar",
    image: "/images/food/firin-sutlac.jpg",
    weight: "200 gr",
    allergens: ["Süt ürünleri", "Gluten"],
    tags: ["Sütlü Tatlı"],
    status: "active",
  },
  {
    id: "keskul",
    name: "Keşkül",
    description: "Badem aroması ve Hindistan ceviziyle tamamlanan Osmanlı usulü sütlü tatlı.",
    price: 145,
    categoryId: "dessert",
    category: "Tatlılar",
    image: "/images/food/firin-sutlac.jpg",
    weight: "200 gr",
    allergens: ["Süt ürünleri", "Badem"],
    tags: ["Sütlü Tatlı"],
    status: "active",
  },
  {
    id: "irmik-helvasi",
    name: "İrmik Helvası",
    description: "Tereyağı ve çam fıstığıyla kavrulan, sıcak servis edilen tane tane irmik helvası.",
    price: 130,
    categoryId: "dessert",
    category: "Tatlılar",
    image: "/images/food/firin-sutlac.jpg",
    weight: "180 gr",
    allergens: ["Gluten", "Süt ürünleri", "Çam fıstığı"],
    tags: ["Sıcak Tatlı"],
    status: "active",
  },
  {
    id: "kabak-tatlisi",
    name: "Tahinli Kabak Tatlısı",
    description: "Kendi suyunda ağır ağır pişen bal kabağı, tahin ve cevizle servis edilir.",
    price: 160,
    categoryId: "dessert",
    category: "Tatlılar",
    image: "/images/food/firin-sutlac.jpg",
    weight: "220 gr",
    allergens: ["Susam", "Ceviz"],
    tags: ["Vegan", "Mevsimlik"],
    status: "active",
  },
  {
    id: "ayva-tatlisi",
    name: "Ayva Tatlısı",
    description: "Karanfil ve tarçınla pişirilen ayva, kaymak ve ceviz eşliğinde servis edilir.",
    price: 175,
    categoryId: "dessert",
    category: "Tatlılar",
    image: "/images/food/firin-sutlac.jpg",
    weight: "240 gr",
    allergens: ["Süt ürünleri", "Ceviz"],
    tags: ["Mevsimlik"],
    status: "sold-out",
  },
  {
    id: "revani",
    name: "Revani",
    description: "İrmikli yumuşak kekin limon kokulu şerbetle buluştuğu klasik lokanta tatlısı.",
    price: 135,
    categoryId: "dessert",
    category: "Tatlılar",
    image: "/images/food/firin-sutlac.jpg",
    weight: "180 gr",
    allergens: ["Gluten", "Yumurta", "Süt ürünleri"],
    tags: ["Şerbetli"],
    status: "active",
  },
  {
    id: "ekmek-kadayifi",
    name: "Kaymaklı Ekmek Kadayıfı",
    description: "Karamelize şerbetle dinlendirilen ekmek kadayıfı, manda kaymağıyla servis edilir.",
    price: 180,
    categoryId: "dessert",
    category: "Tatlılar",
    image: "/images/food/firin-sutlac.jpg",
    weight: "220 gr",
    allergens: ["Gluten", "Süt ürünleri"],
    tags: ["Bursa Lezzeti", "Şerbetli"],
    status: "active",
  },
  {
    id: "cevizli-baklava",
    name: "Cevizli Baklava",
    description: "İncecik açılmış katlar, bol ceviz ve sade yağla hazırlanan çıtır baklava.",
    price: 220,
    categoryId: "dessert",
    category: "Tatlılar",
    image: "/images/food/firin-sutlac.jpg",
    weight: "200 gr",
    allergens: ["Gluten", "Süt ürünleri", "Ceviz"],
    tags: ["Şerbetli", "Paylaşmalık"],
    status: "active",
    featured: true,
  },
];
