"use client";

import { useCallback } from "react";
import { ArrowLeft, Boxes } from "lucide-react";
import Link from "next/link";

import { LoadingState, ErrorState, EmptyState } from "@/components/shared/data-states";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { ApiResult } from "@/lib/api/response";
import { movementLabel } from "@/lib/domain/erp-workspaces";
import { useApiResource } from "@/lib/hooks/use-api-resource";

interface Detail { item:{name:string;category:string|null;baseUnit:string;reorderLevel:string;negativeStockPolicy:string;isActive:boolean};balances:{warehouse:string;quantity:string}[];movements:{id:string;occurredAt:string;warehouse:string;movementType:string;quantityDelta:string;sourceType:string;reference:string|null;staff:string|null;reason:string|null}[];pagination:{total:number} }

export function InventoryDetailManager({itemId}:{itemId:string}){const load=useCallback(async(signal:AbortSignal)=>{const response=await fetch(`/api/admin/erp/inventory/${itemId}`,{credentials:"same-origin",cache:"no-store",signal});const payload=await response.json() as ApiResult<Detail>;if(!response.ok||!payload.success)throw new Error(payload.success?"Stok ayrıntısı alınamadı.":payload.error.message);return payload.data;},[itemId]);const resource=useApiResource(load);const data=resource.data;if(resource.loading&&!data)return <LoadingState rows={6}/>;if(resource.error&&!data)return <ErrorState title="Stok kalemi yüklenemedi" description={resource.error.message} onRetry={()=>void resource.refetch()}/>;if(!data)return null;return <div className="space-y-5"><Button nativeButton={false} variant="ghost" render={<Link href="/admin/inventory"/>}><ArrowLeft className="size-4"/>Stok listesi</Button><div><h2 className="font-heading text-2xl font-semibold">{data.item.name}</h2><p className="text-sm text-muted-foreground">{data.item.category??"Grupsuz"} · Temel birim {data.item.baseUnit} · Negatif stok: {data.item.negativeStockPolicy==="BLOCK"?"Engelle":"Uyar"}</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.balances.map(balance=><Card key={balance.warehouse}><CardHeader className="pb-2"><CardTitle className="text-sm">{balance.warehouse}</CardTitle></CardHeader><CardContent><strong className="text-xl tabular-nums">{balance.quantity} {data.item.baseUnit}</strong></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Stok hareket geçmişi</CardTitle></CardHeader><CardContent className="p-0">{data.movements.length?<div className="overflow-x-auto"><table className="w-full min-w-[880px] text-sm"><thead><tr className="border-y bg-muted/45 text-left text-xs text-muted-foreground"><th className="px-4 py-3">Tarih</th><th className="px-4 py-3">Depo</th><th className="px-4 py-3">İşlem</th><th className="px-4 py-3">Miktar</th><th className="px-4 py-3">Birim</th><th className="px-4 py-3">Referans</th><th className="px-4 py-3">Personel</th><th className="px-4 py-3">Açıklama</th></tr></thead><tbody>{data.movements.map(m=><tr key={m.id} className="border-b last:border-0"><td className="px-4 py-3">{new Intl.DateTimeFormat("tr-TR",{dateStyle:"short",timeStyle:"short"}).format(new Date(m.occurredAt))}</td><td className="px-4 py-3">{m.warehouse}</td><td className="px-4 py-3">{movementLabel(m.movementType)}</td><td className="px-4 py-3 font-mono">{m.quantityDelta}</td><td className="px-4 py-3">{data.item.baseUnit}</td><td className="px-4 py-3">{m.reference?`${m.sourceType} kaydı`:m.sourceType}</td><td className="px-4 py-3">{m.staff??"Sistem"}</td><td className="px-4 py-3">{m.reason??"Açıklama yok"}</td></tr>)}</tbody></table></div>:<EmptyState icon={Boxes} title="Hareket yok" description="Bu stok kalemi için henüz stok hareketi bulunmuyor."/>}</CardContent></Card></div>}
